# Variables
@base_url=http://localhost:3333

###

# GET HEALTH
GET {{base_url}}/health


###

# GET USERS
GET {{base_url}}/users

###

# POST USER
POST {{base_url}}/users
Accept: application/json
Content-Type: application/json

{
    "email": "nicolas.araujo@mail.net",
    "name": "Nicolas Araujo",
    "password": "admin"
}

###

# UPDATE USER
PUT {{base_url}}/users/4
Accept: application/json
Content-Type: application/json

{
    "new_password": "admin2",
    "new_password_confirmation": "admin2",
    "current_password": "admin"
}

###

# DELETE USER
DELETE {{base_url}}/users/1

###

GET https://viacep.com.br/ws/58410280/json/

###

# GET ALL MODELS
GET {{base_url}}/models

###

POST {{base_url}}/cities/update-all

###

POST {{base_url}}/departments
Accept: application/json
Content-Type: application/json

{
    "name": "Administrativo",
    "description": "Departamento Administrativo",
    "created_by": 4
}

###

POST {{base_url}}/cost_centers
Accept: application/json
Content-Type: application/json

{
    "name": "GERENCIA DE UNIDADE 01",
    "description": "Centro de custo da Gerencia de Unidade 01",
    "department_id": 1,
    "created_by": 4
}

###

GET {{base_url}}/actions

###

POST {{base_url}}/actions
Accept: application/json
Content-Type: application/json

{
    "action": "read",
    "created_by": 4
}

###

GET https://servicodados.ibge.gov.br/api/v1/localidades/municipios

###

### Login to get token
POST {{base_url}}/users/login
Content-Type: application/json

{
  "email": "nicolas.araujo@mail.net",
  "password": "admin2"
}

### Save token
> {% client.global.set("token", response.body.token) %}
@token = {{token}}


### Protected route (/me) – use saved token
GET {{base_url}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJuaWNvbGFzLmFyYXVqb0BtYWlsLm5ldCIsIm5hbWUiOiJOaWNvbGFzIEFyYXVqbyIsImlhdCI6MTc1NDIzNzQyNywiZXhwIjoxNzU0MjM4MzI3fQ.G--SroAf-Hmy3POMYPohpS7XVKU2FobIsGyoEF1RKkU

###

POST {{base_url}}/users/refresh

###

POST {{base_url}}/users/logout